## Steps
## 1.Preprocessing
## 2.Train Test Split
## 3.BOW,TFIDF,WordVec
## 4.Train ML Algorithms

In [2]:
##Load the dataset
import pandas as pd
data=pd.read_csv('all_kindle_review.csv')

In [3]:
data.head()

Unnamed: 0.1  Unnamed: 0        asin  helpful  rating  \
0             0       11539  B0033UV8HI  [8, 10]       3   
1             1        5957  B002HJV4DE   [1, 1]       5   
2             2        9146  B002ZG96I4   [0, 0]       3   
3             3        7038  B002QHWOEU   [1, 3]       3   
4             4        1776  B001A06VJ8   [0, 1]       4   

                                          reviewText   reviewTime  \
0  Jace Rankin may be short, but he's nothing to ...   09 2, 2010   
1  Great short read.  I didn't want to put it dow...   10 8, 2013   
2  I'll start by saying this is the first of four...  04 11, 2014   
3  Aggie is Angela Lansbury who carries pocketboo...   07 5, 2014   
4  I did not expect this type of book to be in li...  12 31, 2012   

       reviewerID  reviewerName                   summary  unixReviewTime  
0  A3HHXRELK8BHQG        Ridley  Entertaining But Average      1283385600  
1  A2RGNZ0TRF578I  Holly Butler   Terrific menage scenes!      1381190400  
2  A3S0H2HV6U1I7F       Merissa          Snapdragon Alley      1397174400  
3   AC4OQW3GZ919J    Cleargrace    very light murder cozy      1404518400  
4  A3C9V987IQHOQD      Rjostler                      Book      1356912000

In [4]:
data=data[['reviewText','rating']]

In [5]:
data.head()

reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       3
1  Great short read.  I didn't want to put it dow...       5
2  I'll start by saying this is the first of four...       3
3  Aggie is Angela Lansbury who carries pocketboo...       3
4  I did not expect this type of book to be in li...       4

In [6]:
data.shape

(12000, 2)

In [7]:
## missing values
data.isnull().sum()

reviewText    0
rating        0
dtype: int64

In [8]:
## unique rating
data['rating'].unique()

array([3, 5, 4, 2, 1])

In [9]:
data['rating'].value_counts()

rating
5    3000
4    3000
3    2000
2    2000
1    2000
Name: count, dtype: int64

In [10]:
## preprocessing and cleaning
## positive review is 1 and negative review is 0
data['rating']=data['rating'].apply(lambda x:0 if x<3 else 1)

In [11]:
data

reviewText  rating
0      Jace Rankin may be short, but he's nothing to ...       1
1      Great short read.  I didn't want to put it dow...       1
2      I'll start by saying this is the first of four...       1
3      Aggie is Angela Lansbury who carries pocketboo...       1
4      I did not expect this type of book to be in li...       1
...                                                  ...     ...
11995  Valentine cupid is a vampire- Jena and Ian ano...       1
11996  I have read all seven books in this series. Ap...       1
11997  This book really just wasn't my cuppa.  The si...       1
11998  tried to use it to charge my kindle, it didn't...       0
11999  Taking Instruction is a look into the often hi...       1

[12000 rows x 2 columns]

In [12]:
data['rating'].unique()

array([1, 0])

In [13]:
data['rating'].value_counts()

rating
1    8000
0    4000
Name: count, dtype: int64

In [14]:
## Lower all the cases
data['reviewText']=data['reviewText'].str.lower()
data.head()

reviewText  rating
0  jace rankin may be short, but he's nothing to ...       1
1  great short read.  i didn't want to put it dow...       1
2  i'll start by saying this is the first of four...       1
3  aggie is angela lansbury who carries pocketboo...       1
4  i did not expect this type of book to be in li...       1

In [15]:
data['reviewText']

0        jace rankin may be short, but he's nothing to ...
1        great short read.  i didn't want to put it dow...
2        i'll start by saying this is the first of four...
3        aggie is angela lansbury who carries pocketboo...
4        i did not expect this type of book to be in li...
                               ...                        
11995    valentine cupid is a vampire- jena and ian ano...
11996    i have read all seven books in this series. ap...
11997    this book really just wasn't my cuppa.  the si...
11998    tried to use it to charge my kindle, it didn't...
11999    taking instruction is a look into the often hi...
Name: reviewText, Length: 12000, dtype: object

In [16]:
import re
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [17]:
from bs4 import BeautifulSoup


In [18]:
!pip install lxml

In [19]:
## Removing special characters
data['reviewText']=data['reviewText'].apply(lambda x:re.sub('[^a-z A-z 0-9-]+', '',x))
## Remove the stopswords
data['reviewText']=data['reviewText'].apply(lambda x:" ".join([y for y in x.split() if y not in stopwords.words('english')]))
## Remove url
data['reviewText']=data['reviewText'].apply(lambda x: re.sub(r'(http|https|ftp|ssh)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?', '' , str(x)))
## Remove html tags
data['reviewText']=data['reviewText'].apply(lambda x: BeautifulSoup(x, 'html.parser').get_text())
## Remove any additional spaces
data['reviewText']=data['reviewText'].apply(lambda x: " ".join(x.split()))

<ipython-input-19-b82e9c482402>:8: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  data['reviewText']=data['reviewText'].apply(lambda x: BeautifulSoup(x, 'html.parser').get_text())


In [20]:
data.head()

reviewText  rating
0  jace rankin may short hes nothing mess man hau...       1
1  great short read didnt want put read one sitti...       1
2  ill start saying first four books wasnt expect...       1
3  aggie angela lansbury carries pocketbooks inst...       1
4  expect type book library pleased find price right       1

In [21]:
## Lemmatizer
from nltk.stem import WordNetLemmatizer

In [23]:
import nltk

In [22]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [24]:
lemmatizer=WordNetLemmatizer()

In [25]:
def lemmatize_words(text):
    return " ".join([lemmatizer.lemmatize(word) for word in text.split()])

In [26]:
data['reviewText']=data['reviewText'].apply(lambda x:lemmatize_words(x))

In [27]:
data.head()

reviewText  rating
0  jace rankin may short he nothing mess man haul...       1
1  great short read didnt want put read one sitti...       1
2  ill start saying first four book wasnt expecti...       1
3  aggie angela lansbury carry pocketbook instead...       1
4  expect type book library pleased find price right       1

In [221]:
## Train Test Split

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test= train_test_split(data['reviewText'],data['rating'],
                                              test_size=0.20)


In [29]:
from sklearn.feature_extraction.text import CountVectorizer
bow=CountVectorizer()
X_train_bow=bow.fit_transform(X_train).toarray()
X_test_bow=bow.transform(X_test).toarray()

In [30]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
X_train_tfidf=tfidf.fit_transform(X_train).toarray()
X_test_tfidf=tfidf.transform(X_test).toarray()


In [31]:
X_train_bow

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [32]:
X_train_tfidf

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.17164468, 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [33]:
from sklearn.naive_bayes import GaussianNB
nb_model_bow=GaussianNB().fit(X_train_bow,Y_train)
nb_model_tfidf=GaussianNB().fit(X_train_tfidf,Y_train)

In [34]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [35]:
y_pred_bow=nb_model_bow.predict(X_test_bow)

In [36]:
y_pred_tfidf=nb_model_bow.predict(X_test_tfidf)


In [37]:
confusion_matrix(Y_test,y_pred_bow)

array([[503, 284],
       [728, 885]])

In [38]:
print("BOW accuracy: ",accuracy_score(Y_test,y_pred_bow))

BOW accuracy:  0.5783333333333334


In [39]:

confusion_matrix(Y_test,y_pred_tfidf)

array([[497, 290],
       [721, 892]])

In [40]:
print("TFIDF accuracy: ",accuracy_score(Y_test,y_pred_tfidf))

TFIDF accuracy:  0.57875


In [41]:
!pip install gensim

In [42]:
import gensim
from gensim.models import Word2Vec

In [43]:
from gensim.models import KeyedVectors

In [44]:
import gensim.downloader as api

In [51]:
import nltk

In [234]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [45]:
wv=api.load('word2vec-google-news-300')
vec_king= wv['king']
vec_king

[==================================================] 100.0% 1662.8/1662.8MB downloaded


array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [243]:
import nltk
from nltk.tokenize import word_tokenize

# Make sure you have the original text data
X_train_tokens = X_train.apply(word_tokenize)
X_test_tokens = X_test.apply(word_tokenize)

In [239]:
from gensim.models import Word2Vec

# Train Word2Vec model
word2vec_model=gensim.models.Word2Vec(X_train_tokens)
# Transform the tokens into Word2Vec vectors
X_train_word2vec = X_train_tokens.apply(lambda x: np.mean([word2vec_model.wv[word] for word in x if word in word2vec_model.wv], axis=0))
X_test_word2vec = X_test_tokens.apply(lambda x: np.mean([word2vec_model.wv[word] for word in x if word in word2vec_model.wv], axis=0))


In [241]:
from sklearn.naive_bayes import GaussianNB

# Convert the pandas Series to numpy arrays
X_train_word2vec = np.array(X_train_word2vec.tolist())
X_test_word2vec = np.array(X_test_word2vec.tolist())

# Train the model
nb_model_word2vec = GaussianNB().fit(X_train_word2vec, y_train)

# Make predictions
y_pred_word2vec = nb_model_word2vec.predict(X_test_word2vec)

# Evaluate the model
from sklearn.metrics import accuracy_score, confusion_matrix

print("Word2Vec accuracy: ", accuracy_score(y_test, y_pred_word2vec))
print(confusion_matrix(y_test, y_pred_word2vec))


Word2Vec accuracy:  0.6375
[[1473  122]
 [ 748   57]]
